[default]
log_debug=true

[rdo]
auth_url = "http://kubernetes3:35357/v3"
os_region_name = "wuhan"
project_domain_name = "default"
project_name = "admin"
user_domain_name = "default"
username = "admin"
password = "admin"
